### ISSUE TITLE
Refresh friends' Twitter avatars on a regular basis

### ISSUE THREAD

**Issue by devonzuegel** [devonzuegel/smallworld#15]
When friends update their Twitter profile pictures, Small World currently does not update the url to the new profile picture. Twitter deletes the old picture files, which results in a "file not found":

<img width="435" alt="image" src="https://user-images.githubusercontent.com/6979755/187036816-9be3ba7b-9fa7-4785-bda5-143719baec50.png">

**Comment by prigoose** [comment]
I think I'm seeing the same bug. When I look at the map, I see a bunch of empty white circles. 
<img width="560" alt="Screen Shot 2022-09-30 at 4 42 10 PM" src="https://user-images.githubusercontent.com/34298715/193353356-a748c9c0-0f2a-4303-bf22-e88e475e3c0b.png">

**Comment by devonzuegel** [comment]
Thanks for the bug report! I'm working on a fix now.

In the meantime, here's a temporary workaround:
1. Go to https://smallworld.kiwi#debug
2. Scroll down and click "toggle debug"
3. Click the button that says "refresh friends"
4. Then it'll take a few seconds, and your friends will re-populate and the images will be fixed

**Comment by devonzuegel** [comment]
Ok it's fixed now! Thanks for reporting the bug, and let me know if you see anything else that's funky.
