### ISSUE TITLE
limit emails to actually nearby friends

### ISSUE THREAD

**Issue by fratrik** [devonzuegel/smallworld#18]
I'm getting daily emails about all my follows that update their location.

I thought I was only going to get an email if someone I follow updates to be near me.

**Comment by devonzuegel** [comment]
Thanks for the feedback, I see why that would be unexpected! I'll think about how to handle this better.

**Comment by devonzuegel** [comment]
I just finished implementing this feature! You can change your preferences by going to https://smallworld.kiwi/settings:

<img width="533" alt="image" src="https://github.com/devonzuegel/smallworld/assets/6979755/887bca8d-a24a-44cc-a917-1ff83284d329">

Let me know if you experience any bugs!
