### ISSUE TITLE
Validate phone before requesting SMS pin

### ISSUE THREAD

**Issue by devonzuegel** [devonzuegel/smallworld#29]
If you don't enter any phone number and click `Sign in`, it'll open up the SMS code field. Instead, it should first validate that the phone number is formatted properly.

Here's how it looks right now:

_Step 1:_
<img width="203" alt="image" src="https://github.com/devonzuegel/smallworld/assets/6979755/f8186e79-888f-4937-be8c-71418cd41931">

_Step 2:_
<img width="202" alt="image" src="https://github.com/devonzuegel/smallworld/assets/6979755/9416d8e1-7502-4890-bab9-97d9bc60f5e9">

**Comment by bensu** [comment]
Fixed in branch
