### ISSUE TITLE
Remove “area” from Twitter bio location

### ISSUE THREAD

**Issue by scottleibrand** [devonzuegel/smallworld#9]
![67EEDDF3-E304-4960-A190-B2B192E0677F](https://user-images.githubusercontent.com/6982790/172759704-38d426eb-463a-4c36-a443-f14da79a46b7.jpeg)

My bio says “Seattle area”, which gets geolocated to northwestern Mexico. Preferred fix would be to trim off “ area” from the end of all bio locations.

**Comment by scottleibrand** [comment]
When I add Seattle as a location manually, that works fine, but obviously it won’t help any of my Twitter friends see that I’m based there.

**Comment by devonzuegel** [comment]
Good suggestion, thank you! I just deployed a fix for this, lmk if it works for you.

**Comment by scottleibrand** [comment]
Yep, after logging out and back in, it located me correctly. Thx!
